// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxWTHAvEU9k6Mm0GoBIb3nDxeYIGjc90s',
    appId: '1:873381944852:web:7cb7347462946874f3d101',
    messagingSenderId: '873381944852',
    projectId: 'fir-qr-4caf7',
    authDomain: 'fir-qr-4caf7.firebaseapp.com',
    storageBucket: 'fir-qr-4caf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOIaYwhTfbkNERDfmBBlEEL1YOgZFhLMg',
    appId: '1:873381944852:android:2ad729834956e517f3d101',
    messagingSenderId: '873381944852',
    projectId: 'fir-qr-4caf7',
    storageBucket: 'fir-qr-4caf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ7Rc4tMa_ADMDw0gsLvnXiTww3odVDiU',
    appId: '1:873381944852:ios:862806009945bb70f3d101',
    messagingSenderId: '873381944852',
    projectId: 'fir-qr-4caf7',
    storageBucket: 'fir-qr-4caf7.appspot.com',
    iosClientId: '873381944852-uflm8dr0ld0eci35miu82ogs9quj9vqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoQr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ7Rc4tMa_ADMDw0gsLvnXiTww3odVDiU',
    appId: '1:873381944852:ios:862806009945bb70f3d101',
    messagingSenderId: '873381944852',
    projectId: 'fir-qr-4caf7',
    storageBucket: 'fir-qr-4caf7.appspot.com',
    iosClientId: '873381944852-uflm8dr0ld0eci35miu82ogs9quj9vqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoQr',
  );
}
